spring:
  profiles:
    active: 
      - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: microservicecloud-config-client
eureka:
  client:
    server-url:
      defaultZone: http://eureka-dev.com:7001/eureka/,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
---
server:
  port: 8020
spring:
  profiles: test
  application:
    name: microservicecloud-config-client
eureka:
  client:
    server-url:
      defaultZone: http://eureka-dev.com:7001/eureka/,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka